<h2 class="widget-title"> Testimonials </h2>

<?php $baseUrl = $this->getBaseUrl(); ?><?php
$mediaUrl = $this->getMediaUrl();
$testimonialrecords = $this->getCollection();
if ($testimonialrecords && count($testimonialrecords)) {
    ?>
    <div class="testimonialslider">
        <div class="slides">
            <?php
            foreach ($testimonialrecords as $tetimonial) { ?>
                <div class="testimonial-widget item">
                    <div class="quote">
                        <p><?php echo $tetimonial->getData('testimonial'); ?></p>
                    </div>
                    <div class="student">
                        <div class="photo">
                            <?php $path = $tetimonial->getData('avatar_path'); ?>
                            <?php if (isset($path) && $path != ''): ?>
                                <img src="<?php echo $mediaUrl . $tetimonial->getData('avatar_path'); ?>" width="100"
                                     height="100"/>
                            <?php else: ?>
                                <img src="<?php echo $this->getDefaultImage(); ?>" width="100" height="100"/>
                            <?php endif; ?>
                        </div>
                        <p><?php echo $tetimonial->getData('name'); ?></p>
                        <p><?php //echo $tetimonial->getData('email'); ?></p>
                    </div>
                </div>

                <?php
            }
            ?>
        </div>
    </div>
    <?php
}
?>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
<div class="add-new-testimonial">
    <a class="action submit primary" data-toggle="modal" href="#responsive">
        <span>Add New Testimonial</span>
    </a>
</div>

<script>
    require([
        'jquery',
        'testimonialSlider', 'testimonialmodal'
    ], function ($) {
        $(".testimonialslider .slides").owlCarousel({
            autoPlay: 5000,
            items: 3,
            itemsDesktop: [1199, 3],
            itemsTablet: [768, 2],
            itemsDesktopSmall: [979, 2],
            itemsMobile: [750, 1],
            pagination: true,
            navigation: false
        });
    });
</script>
<div id="responsive" class="modal fade bootstrap-dialog type-primary" tabindex="-1" data-width="760">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div class="bootstrap-dialog-title">Add Testimonial</div>
            </div>
            <div class="modal-body">            <?php $users = $this->getcustomerSession();
                $firstname = $users['firstname'];
                $email = $users['email'];
                $cid = $users['entity_id']; ?>
                <form method="POST" enctype='multipart/form-data'
                      action="<?php echo $this->getUrl('testimonials/index/post'); ?>"
                      data-hasrequired="<?php echo __('* Required Fields') ?>"
                      data-mage-init='{"validation":{}}'>                    <?php if (isset($cid) && $cid != '') { ?>
                        <input type="hidden" name="customer_id"
                               value="<?php echo $cid; ?>">                            <?php } ?>
                    <fieldset class="fieldset">
                        <div class="field name required"><label class="label"
                                                                for="name"><span><?php echo __('Name') ?></span></label>
                            <div class="control"><input name="name" id="name" title="<?php echo __('name') ?>"
                                                        value="<?php if (isset($firstname) && $firstname != '') {
                                                            echo $firstname;
                                                        } else {
                                                            echo '';
                                                        } ?>" class="input-text" type="text"
                                                        data-validate="{required:true}"/></div>
                        </div>
                        <div class="field email required"><label class="label"
                                                                 for="name"><span><?php echo __('Email') ?></span></label>
                            <div class="control"><input name="email" id="email" title="<?php echo __('email') ?>"
                                                        value="<?php if (isset($email) && $email != '') {
                                                            echo $email;
                                                        } else {
                                                            echo '';
                                                        } ?>" class="input-text" type="text"
                                                        data-validate="{required:true}"/></div>
                        </div>
                        <div class="field avatar_path"><label class="label"
                                                              for="avatar_path"><span><?php echo __('Upload Avatar') ?></span></label>
                            <div class="control"><input type="file" name="avatar_path" id="avatar_path"
                                                        title="<?php echo __('Upload Avatar') ?>"/></div>
                        </div>
                        <div class="field testimonial required"><label class="label"
                                                                       for="testimonial"><span><?php echo __('Testimonial') ?></span></label>
                            <div class="control"><textarea rows="4" cols="50" data-validate="{required:true}" rows="4"
                                                           cols="50" name="testimonial" id="testimonial"
                                                           title="<?php echo __('Testimonial') ?>"></textarea></div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                                    <span><?php echo __('Submit') ?></span></button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>